config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [:create]
  resources :products, only: [:index, :new, :create]
  resources :restaurants
  devise_for :users
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :user

  enum status: [:pending, :done]
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :restaurant
  has_many :orders

  validates :name, presence: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :products
  belongs_to :user

  def total_of_products
    products.count
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :restaurant
  has_many :orders
  enum role: [:admin, :restaurant, :customer]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @email = user_signed_in? ? current_user.email : 'undefined'
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    #binding.pry
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    @order.status = :pending

    if @order.save
      flash[:notice] = "Pedido criado com sucesso!"
      RestaurantNotifierJob.perform_later(current_user.id)
    else
      flash[:notice] = "Falha ao criar pedido!"
    end
    redirect_to root_path
  end

  private

  def order_params
    params.permit(:product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html{
          redirect_to products_path, notice: 'Produto criado'
        }
      else
        format.html{ render :new }
      end
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :value, :restaurant_id)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy ]

  # GET /restaurants or /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: "Restaurant was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: "Restaurant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/home/_customer.html.erb
<p>Restaurantes</p>
<table>
  <thead>
    <tr>
      <th>nome</th>
    </tr>
  </thead>

  <tbody>
    <% Restaurant.all.each do |r| %>
      <tr>
        <td><%= r.name %></td>
        <table>
          <tbody>
            <% r.products.each do |p| %>
              <tr>
                <%= form_tag('/orders') do   %>
                  <%= hidden_field_tag :product_id, p.id %>
                  <td>-> <%= p.name %></td>
                  <td>-> <%= p.value %></td>
                  <td><%= submit_tag 'Pedir' %> </td>

                <% end %>

              </tr>
            <% end %>
          </tbody>
        </table>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/home/_restaurant.html.erb
<p>Seus produtos, <%= current_user.restaurant.name %>! </p>
<%= var %>
<table>
  <thead>
    <tr>
      <th>nome</th>
      <th>valor</th>
    </tr>
  </thead>
  <tbody>
    <% current_user.restaurant.products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.value %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<p>Hello <%= @email  %></p>

<% if user_signed_in? %>
  <% if current_user.restaurant? %>
    <%= render 'restaurant', var: 124 %>
  <% elsif current_user.customer? %>
    <%= render 'customer' %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ieat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :restaurant %>
    <%= form.collection_select(:restaurant_id, Restaurant.order(:name), :id, :name, include_blank: true) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/index.html.erb
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th> Nome</th>
      <th> Valor</th>
      <th> Restaurante</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |p| %>
    <tr>
      <th><%= p.name%></th>
      <th><%= p.value%></th>
      <th><%= p.restaurant.name%></th>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>Novo Produto</h1>
<%= render 'form', product: @product %>

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
        <% restaurant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :user %>
    <%= form.collection_select(:user_id, User.restaurant, :id, :email, include_blank: true) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Total of products</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.total_of_products %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>